Adapt DPsim to deploy it in Mybinder
sogno-platform/dpsim pull request #323
Opened 2024-10-21 08:59 UTC by pipeacosta

Based on a past PR from @stv0g . I made some changes recently and was able to deploy DPsim successfully in [Mybinder](https://mybinder.org/v2/gh/sogno-platform/dpsim/mybinder?labpath=examples%2FNotebooks%2FQuickstart+Guide.ipynb). This requires to place a new Dockerfile (adapter from the Fedora-based [Dockerfile](https://github.com/sogno-platform/dpsim/blob/mybinder/packaging/Docker/Dockerfile)) in the dpsim's root folder. Because this is intended to offer another way of end users to interact with DPsim, I think one important question here is: Should we keep this functionality as part of DPsim's main repo, or should we implement it in a separate repo?

2024-12-21 14:04 UTC, pipeacosta commented
> Wow, there are a lot of conflicts :( Do you think we can resolve them @pipeacosta? Or would it be better to start from scratch?

Hi @stv0g. Do you mean the fact that the commit history is a bit messed?

2024-12-21 15:43 UTC, stv0g commented
Yes, partially. This PR has 250 commits :o

But also:

![Screenshot 2024-12-21 at 16 43 32](https://github.com/user-attachments/assets/f611799e-5460-48d1-97d1-3ccfcd2ce174)

2024-12-23 15:48 UTC, pipeacosta commented
> Yes, partially. This PR has 250 commits :o
> 
> But also:
> 
> ![Screenshot 2024-12-21 at 16 43 32](https://private-user-images.githubusercontent.com/285829/397937549-f611799e-5460-48d1-97d1-3ccfcd2ce174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjkxNjcsIm5iZiI6MTczNDk2ODg2NywicGF0aCI6Ii8yODU4MjkvMzk3OTM3NTQ5LWY2MTE3OTllLTU0NjAtNDhkMS05N2QxLTNjY2ZjZDJjZTE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNTQ3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2I4YWM2YTYyNmIyZjZjZjJiNDNiZWRjZTc5MjQ2NGY3ZjBmNGViMWVjM2NjNmZhZmY4ZTYxMTUxYjZjN2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5PEviX9HBe_RG7tcc9PYSC_cAAutbDxRVjwpXH9fh4w)

Hi @stv0g. Does it look better now?

2025-01-28 17:05 UTC, stv0g requested changes

2025-01-28 17:05 UTC, stv0g commented on .gitmodules
> +[submodule "examples/Notebooks/MSP-lecture"]
@m-mirz Whats you stand on adding this as a submodule?

2025-01-28 17:05 UTC, stv0g commented on Dockerfile
> +FROM fedora:36 AS base
Current version of Fedora is 41.
Fedora 36 has been released almost 3 years ago (2022-05!)

2025-01-28 17:05 UTC, stv0g commented on Dockerfile
> +ADD requirements.txt .
This is currently breaking the CI pipeline. I think we should use COPY here.

2025-01-28 17:05 UTC, stv0g commented
Please also un-draft the PR once its ready for review/merge 👍🏻

2025-01-29 07:49 UTC, pipeacosta commented on Dockerfile
> +FROM fedora:36 AS base
I kept this version as it was, I would need support to decide if using version 41 does not conflict with any dependency. @m-mirz

2025-01-29 07:54 UTC, leonardocarreras commented on Dockerfile
> +FROM fedora:36 AS base
I am compiling in 41 regularly, might be able to support if needed @pipeacosta . The compiler is a lot stricter now, that is the main problem in general.

2025-01-29 08:47 UTC, pipeacosta commented on Dockerfile
> +FROM fedora:36 AS base
At this point, I am thinking that this could be the subject of a different PR,  what do you think?

2025-01-29 08:49 UTC, leonardocarreras commented on Dockerfile
> +FROM fedora:36 AS base
I think we might want to update all containers, at some point and not only fedora ones. In my opinion yes, but no idea what the people say...

2025-01-29 22:11 UTC, stv0g commented on README.md
> +Click the badge below to explore the interactive Jupyter notebooks in your browser:
```suggestion
## Getting started using Binder

Click the badge below to explore the interactive Jupyter notebooks in your browser:
```

2025-01-29 22:14 UTC, stv0g commented on apt.txt
Is this file necessary? I think there are already several other places where we define required dependencies:

- https://github.com/sogno-platform/dpsim/blob/61dd43639f8830a2e5e41ced816f12ea0ffdce25/packaging/Shell/install-fedora-deps.sh
- https://github.com/sogno-platform/dpsim/blob/master/packaging/Shell/install-ubuntu-deps.sh

I dont think adding another one is good practice, as it will inevitable become out-of-date and/or out-of-sync with the remaining ones.

2025-01-29 22:15 UTC, stv0g requested changes
Looks good so far :) I left one more comment and I think we should wait for other reviewers.

2025-01-30 11:38 UTC, stv0g submitted a review, later dismissed

2025-01-30 13:33 UTC, pipeacosta commented on .gitmodules
> +[submodule "examples/Notebooks/MSP-lecture"]
Actually I think this is not necessary, DPsim has plenty of examples already

2025-01-30 14:03 UTC, stv0g approved these changes

2025-01-31 12:35 UTC, leonardocarreras commented on setup.py
> +            ['cmake', '--build', '.', '--target', 'dpsimpy', 'dpsimpyvillas'] + build_args, cwd=self.build_temp
I think this will affect all the python builds including the one for pypa. I do not know if this comes with any problem.

2025-03-04 08:32 UTC, stlankes approved these changes

2025-07-05 10:47 UTC, pipeacosta commented
@stv0g @leonardocarreras I think this PR is ready to be merged, could you please have a final look and approve?

2025-07-07 17:12 UTC, leonardocarreras approved these changes
Looks good, but you may need to rebase again

2025-07-07 18:12 UTC, merged

2025-07-08 13:54 UTC, stv0g commented
Unfortunatly launching the Binder does not work for me:

![image](https://github.com/user-attachments/assets/e02ff2dc-b571-44e2-ba1e-6919ee3cf1ed)

@pipeacosta @leonardocarreras Did you test it on our side?

2025-07-08 14:05 UTC, leonardocarreras commented
![image](https://github.com/user-attachments/assets/49540bb7-d4f4-4320-b342-7b3ef30e5d56)
For me it works, did you use the link in the master?

2025-07-08 14:42 UTC, pipeacosta commented
Yesterday it was working perfectly. Today, it failed on my first try, and succeeded on the second one. I also tried from different browsers after that, and worked as well. I will try again tomorrow to see if the problem persists. @stv0g could you please try again and tell us?